generic-service:
  nameOverride: hmpps-digital-prison-reporting-mi

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-digital-prison-reporting-mi
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-digital-prison-reporting-mi-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    DPR_LIB_AWS_STS_ENABLED: true
    DPR_LIB_AWS_DYNAMODB_ENABLED: true
    SENTRY_TRACES_SAMPLE_RATE: '0.05'
    SENTRY_IGNORED_EXCEPTIONS_FOR_TYPE: "org.apache.catalina.connector.ClientAbortException"


  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-digital-prison-reporting-mi:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    redshift-jdbc:
      REDSHIFT_JDBC_USER: "user"
      REDSHIFT_JDBC_PASSWORD: "password"
      REDSHIFT_JDBC_URL: "url"
    hmpps-auth:
      SYSTEM_CLIENT_ID: "system_client_id"
      SYSTEM_CLIENT_SECRET: "system_client_secret"
    redshift-data:
      REDSHIFT_DATA_SECRETARN: "secretarn"
    aurora-missing-report-jdbc:
      AURORA_MISSING_REPORT_JDBC_USER: "user"
      AURORA_MISSING_REPORT_JDBC_PASSWORD: "password"
      AURORA_MISSING_REPORT_JDBC_URL: "url"
    hmpps-digital-prison-reporting-mi-ui-sentry:
      SENTRY_DSN: SENTRY_DSN
      SENTRY_AUTH_TOKEN: SENTRY_AUTH_TOKEN
      SENTRY_RELEASE: RELEASE_GIT_SHA_API

  allowlist:
    cloudplatform-live1-1: 35.178.209.113/32
    cloudplatform-live1-2: 3.8.51.207/32
    cloudplatform-live1-3: 35.177.252.54/32

generic-prometheus-alerts:
  targetApplication: hmpps-digital-prison-reporting-mi
