---
# Per environment values which override defaults in hmpps-digital-prison-reporting-mi/values.yaml

generic-service:
  serviceAccountName: "dpr-reporting-mi-production-cross-iam"
  ingress:
    host: digital-prison-reporting-mi.hmpps.service.justice.gov.uk
  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    AUTHORISED_ROLES: ROLE_PRISONS_REPORTING_USER
    ME_CASELOADS_API_HOST: https://manage-users-api.hmpps.service.justice.gov.uk
    REDSHIFT_DATA_CLUSTER_ID: dpr-redshift-production
    REDSHIFT_DATA_DB: datamart
    REDSHIFT_DATA_S3_LOCATION: dpr-working-production/reports
    DPR_LIB_AWS_ACCOUNTID: "004723187462"
    AURORA_MISSING_REPORT_PORT: 5432
    SENTRY_ENVIRONMENT: production

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: dpr-alerts-prod-alert
