# Per environment values which override defaults in hmpps-digital-prison-reporting-mi/values.yaml

generic-service:
  replicaCount: 2
  serviceAccountName: "dpr-reporting-mi-test-cross-iam"

  ingress:
    host: digital-prison-reporting-mi-test.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    AUTHORISED_ROLES: ROLE_PRISONS_REPORTING_USER
    ME_CASELOADS_API_HOST: https://manage-users-api-dev.hmpps.service.justice.gov.uk
    REDSHIFT_DATA_CLUSTER_ID: dpr-redshift-test
    REDSHIFT_DATA_DB: datamart
    REDSHIFT_DATA_S3_LOCATION: dpr-working-test/reports
    DPR_LIB_AWS_ACCOUNTID: "203591025782"

  allowlist:
    groups:
      - circleci
      - internal

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-digital-prison-reporting-dev
