name: PR preparation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  checks:
    uses: ministryofjustice/HMPPS-REPORTING-WORKFLOWS/.github/workflows/pr_checks.yml@v1
    secrets: inherit
    with:
      java-version: '21'
      java-distribution: 'corretto'
